//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace ISManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }

        [DisplayName("Account ID")]
        public int AccountId { get; set; }

        [Required]
        [DisplayName("Transaction Date")]
        public System.DateTime? transaction_date { get; set; }

        [DisplayName("Capture Date")]
        public System.DateTime capture_date { get; set; }

        [Required]
        [DisplayName("Amount")]
        public decimal amount { get; set; }


        [DisplayName("Description")]
        public string description { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
